### ISSUE TITLE
Add Pytorch Serving component

### ISSUE THREAD

**Issue by tinuxnet** [kf5i/k3ai#22] opened 2020-10-15 08:58 UTC
Could be useful to add support to this component:
https://v0-5.kubeflow.org/docs/components/pytorchserving/
Considering that pytorch is used massively in research and production also.

**Comment by alfsuse** [comment] 2020-10-15 17:51
Closing because a duplicate of Add Pytorch Serving component kf5i/k3ai-plugins#15

**Closed by alfsuse** 2020-10-15 17:51 UTC
Labels: duplicate, enhancement
