### ISSUE TITLE
Add Full Kubeflow Support

### ISSUE THREAD

**Issue by Gsantomaggio** [kf5i/k3ai#17] opened 2020-10-12 11:13 UTC
Add full kubeflow support

**Comment by saiyam1814** [comment] 2020-10-12 11:58
This would be so cool

**Comment by alfsuse** [comment] 2020-10-14 06:48
Closing since it's a duplicate of https://github.com/kf5i/k3ai-plugins/issues/9

**Closed by alfsuse** 2020-10-14 06:48 UTC
Labels: duplicate, enhancement
